# Generated by Django 2.0.2 on 2018-02-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180221_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='category_name', to='blog.Category'),
        ),
    ]
