# Generated by Django 2.0.2 on 2018-02-21 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180221_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
    ]
